/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const NImage: typeof import('naive-ui')['NImage']
  const NTable: typeof import('naive-ui')['NTable']
}
