/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    3rdPartyLibCard: typeof import('./src/components/3rd-party-lib-card.vue')['default']
    404: typeof import('./src/components/404.vue')['default']
    AccHeading: typeof import('./src/components/md-comp/accHeading.vue')['default']
    AIGCWarning: typeof import('./src/components/md-comp/AIGC-Warning.vue')['default']
    AsciinemaWrapper: typeof import('./src/components/md-comp/AsciinemaWrapper.vue')['default']
    BreadCrumbx: typeof import('./src/components/breadCrumbx.vue')['default']
    Card: typeof import('./src/components/md-comp/card.vue')['default']
    CodeBlocks: typeof import('./src/components/md-comp/CodeBlocks.vue')['default']
    ContentDefault: typeof import('./src/components/content-default.vue')['default']
    CursorAnim: typeof import('./src/components/cursor-anim.vue')['default']
    CustomCollapse: typeof import('./src/components/custom-collapse.vue')['default']
    CustomContainer: typeof import('./src/components/md-comp/CustomContainer.vue')['default']
    DirContentMain: typeof import('./src/components/dir-content-main.vue')['default']
    Downloadcard: typeof import('./src/components/md-comp/downloadcard.vue')['default']
    ElementAHandler: typeof import('./src/components/md-comp/element-a-handler.vue')['default']
    IndexAlternativeSwitch: typeof import('./src/components/index-alternative-switch.vue')['default']
    LetterEffects: typeof import('./src/components/md-comp/letter-effects.vue')['default']
    LoadingSkeletons: typeof import('./src/components/LoadingSkeletons.vue')['default']
    MermaidSupport: typeof import('./src/components/md-comp/mermaidSupport.vue')['default']
    NavGithubCk: typeof import('./src/components/nav-github-ck.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NIcon: typeof import('naive-ui')['NIcon']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    Onthispage: typeof import('./src/components/onthispage.vue')['default']
    PasswordContainer: typeof import('./src/components/md-comp/passwordContainer.vue')['default']
    PdfEmbed: typeof import('./src/components/md-comp/pdf-embed.vue')['default']
    PrintNotin: typeof import('./src/components/print-notin.vue')['default']
    QACard: typeof import('./src/components/md-comp/QACard.vue')['default']
    Recite_controller: typeof import('./src/components/md-comp/Recite_controller.vue')['default']
    Recite_Hidden: typeof import('./src/components/md-comp/Recite_Hidden.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/side-nav.vue')['default']
    SwitchLightDark: typeof import('./src/components/switch-light-dark.vue')['default']
    WorkingEnvironmentLabel: typeof import('./src/components/md-comp/working-environment-label.vue')['default']
  }
}
