<template>
<div class="aigc-warning">
  <!-- <img src="@/assets/humbleicons~ai.svg" alt="AI Icon" class="icon" /> -->
    <p>AIGC content.</p>
    <span>
        {{ $props.aigc_level === 'uncansored'?"This content is completely generated by AI, and do not receive any review. Please verify the information before using it." }}

    </span>
</div>
</template>
<script setup>
defineProps({
  aigc_level: {
    type: String,
    default: 'uncansored'
  }
});
</script>