<template>
  <n-alert
    class="aigc-warning"
    show-icon
    :type="level.type"
    :title="level.title"
  >
    <template #icon>
      <n-icon :size="22"><component :is="level.icon" /></n-icon>
    </template>
    <slot>{{ level.message }}</slot>
  </n-alert>
</template>
<script setup>
import { computed } from "vue";
import IconSmartToy from "~icons/material-symbols-light/smart-toy";
import IconNeurology from "~icons/material-symbols-light/neurology";
import IconPsychology from "~icons/material-symbols-light/psychology";

const LEVELS = {
  uncensored: {
    type: "error",
    icon: IconSmartToy,
    title: "AIGC Content (Uncensored)",
    message:
      "This content is completely generated by AI, and do not receive any review. Please verify the information before using it.",
  },
  generated: {
    type: "warning",
    icon: IconNeurology,
    title: "AIGC Content",
    message:
      "This content is generated by AI. Please double-check the information before relying on it.",
  },
  assisted: {
    type: "info",
    icon: IconPsychology,
    title: "AI-Assisted Content",
    message:
      "This content is written with AI assistance and has been reviewed by the author.",
  },
};

const props = defineProps({
  aigcLevel: {
    type: String,
    default: undefined,
  },
});

const level = computed(() => {
  return LEVELS[props.aigcLevel ?? ""] ?? LEVELS.uncensored;
});
</script>

<style scoped>
.aigc-warning {
  margin: 1em 0;
}
</style>
